version: '3.3'
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: gestio
      MYSQL_USER: izan
      MYSQL_PASSWORD: 123456
    ports:
      - 3306:3306
      
  phpmyadmin:
    image: phpmyadmin:latest
    environment:
      PMA_HOST: mysql
    ports:
      - 8090:80
